language: node_js
node_js:
- '6'
script:
- npm run lint
deploy:
  provider: heroku
  app: vuether-api
  api_key:
    secure: MFDbNOiG1Ep54MGWgL6Wnkd4vY5JoxCbNnx57VAG5wvT4vZCTcGqPMtQN+9imLYqzJVTuJyF7+yiOO5DH8mmmMRwgdohBRrcs8GB8yOmS4HOqcDW3R4/TMwaJs+F5ymvQ9wDOXv60kRMlUX6WLgtL7mxZlD4kClJTfrUswM9VasNV5hCRbeSFEbpSXE6Mq4o0tye/QOAQrQgMdhUWwy6apgO/0edbqsTW8q5cLLvsvthpL8MuJEfQIzyDHYnmgBI+ldOxy+0t7K4WAFToFKNNV/R68xjRN0TpbVE9N2XP0mfZsjIQy82weC1jNsvbV3zafcj0Zw6fl7XM6Gp3QfEzo4Ba87x3jVA2jdBsQRUgRbLcXJrSIMdnBNGCvjSPM7lnbA27QHk34nrSvQi7OiG+MtV4nkTYFXdRxJQUVIVypOEnRu3bS5xiI4Cho8++ckok6Pgp4+rBLLRHUcFhsaQv/RzHdVVFx/UiV2EMkN6L60ipqS3x3LSFaj7vWigV5B1qAsde+FtK2MkNCcV3bnUZGXnoiR2ygx7xNB1DRn/xRPqMD1Ht8qgL0Gp/7t06FmZTECxkGY7Jy05XkWKQ621ZzEFd947aq6sQ2QnD9SNkl9NxoYVNZO9UQwUrVe24NPNtUPAQjXXW6w1pU8qjKWs413EfT3Nm+3dwvj7o8XPcZE=
